trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: rauldipeas_sec.gpg
- task: DownloadSecureFile@2
  inputs:
    secureFile: rauldipeas_pub.gpg
- script: |
    gpg --import $(Agent.TempDirectory)/rauldipeas_pub.gpg
    gpg --allow-secret-key-import --import $(Agent.TempDirectory)/rauldipeas_sec.gpg
    bash repo/update-repo.sh
    npm install -g --silent netlify-cli
    netlify deploy --site=005c4fd0-8706-46a9-9d94-55e2c952dc5e --dir=website --prod
  displayName: 'RaDiX - Build APT Repository'

variables:
- group: Netlify
