trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - readme.md

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: rauldipeas_sec.gpg
  - script: gpg --allow-secret-key-import --import $(Agent.TempDirectory)/rauldipeas_sec.gpg
    displayName: 'Import secure GPG'
  - script: bash repo/update-repo.sh
    displayName: 'RaDiX - Build APT Repository'
  - script: sudo apt install -y npm ; sudo npm install -g --silent netlify-cli
    displayName: 'Install Netlify CLI'
  - script: netlify deploy --site=005c4fd0-8706-46a9-9d94-55e2c952dc5e --dir=website --prod
    displayName: 'Netlify deploy'

variables:
  - group: Netlify
