#!/bin/bash
cd /tmp
wget -c http://reaper.fm/files/5.x/reaper5978_linux_x86_64.tar.xz
tar -Jxf reaper*_linux_x86_64.tar.xz;cd reaper_linux_x86_64
./install-reaper.sh --install /opt --integrate-desktop --usr-local-bin-symlink --quiet

#wget -c https://github.com/cfillion/reapack/releases/download/v1.2.1/reaper_reapack64.so -O /tmp/reaper_reapack64.so
#mkdir -p $HOME/.config/REAPER/UserPlugins
#mv -v /tmp/reaper_reapack64.so $HOME/.config/REAPER/UserPlugins

wget -O /opt/REAPER/Plugins/reaper_sws64.so http://www.sws-extension.org/download/pre-release/linux-2.10.0.0/reaper_sws64.so

echo "
Actions=NewProject;ShowAudioConfig;ReaMote;WhatsNew;License;

[Desktop Action NewProject]
Name=REAPER (create new project)
Name[pt_BR]=REAPER (criar novo projeto)
Exec=/opt/REAPER/reaper -new
Icon=cockos-reaper

[Desktop Action ShowAudioConfig]
Name=REAPER (show audio configuration on startup)
Name[pt_BR]=REAPER (mostrar configurações de áudio ao iniciar)
Exec=/opt/REAPER/reaper -audiocfg
Icon=cockos-reaper

[Desktop Action ReaMote]
Name=ReaMote
Exec=/opt/REAPER/reamote-server
Icon=folder-remote

[Desktop Action WhatsNew]
Name=What's new
Name[pt_BR]=O que há de novo?
Exec=xdg-open /opt/REAPER/whatsnew.txt
Icon=text-x-plain

[Desktop Action License]
Name=License and User Agreement
Name[pt_BR]=Licença e contrato de usuário
Exec=xdg-open /opt/REAPER/license.txt
Icon=text-x-plain" >> /usr/local/share/applications/cockos-reaper.desktop
