version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "15:96:54:e7:0a:78:74:1f:13:45:1b:57:ec:9a:60:66"
      - run:
          name: Build APT Repository
          command: bash repo/update-repo.sh
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./website -p
