# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

docker:
      - image: circleci/node:bionic

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
  jobs:
    deploy:
      steps:
        - checkout
        - run:
          name: Build APT Repository
          command: bash repo/update-repo.sh
        - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
        - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./website -p
