version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build APT Repository
          command: |
            wget https://gist.githubusercontent.com/rauldipeas/4c718477023baee2448083b4de263187/raw/31e4617d811369972150226e31bcd6ca4ba71662/rauldipeas_pub.gpg
            wget https://gist.githubusercontent.com/rauldipeas/4c718477023baee2448083b4de263187/raw/31e4617d811369972150226e31bcd6ca4ba71662/rauldipeas_sec.gpg
            gpg --import rauldipeas_pub.gpg
            gpg --allow-secret-key-import --import rauldipeas_sec.gpg
            bash repo/update-repo.sh
            sudo npm install -g --silent netlify-cli
            netlify deploy --site=1e662434-7648-4ef9-a0c4-6866163984a6 --dir=website --prod
