version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
        name: Build APT Repository
        command: bash repo/update-repo.sh
      - run:
        name: Install netlify-cli
        command: sudo npm install -g --silent netlify-cli
      - run:
        name: Deploy to Netlify
        command: netlify deploy --dir=./website -p
